name: Boruc.WeddingWeb.PullRequest-$(FullSemVer)

trigger: none

pr:
  autoCancel: false
  branches:
    include:
    - feature/*
    - bugfix/*
    - hotfix/*
    exclude:
    - master
    - release/*
  drafts: false

pool:
  vmImage: 'ubuntu-latest'

variables:
  GitVersion.SemVer: ''
  
steps:
- task: gitversion/setup@0
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0
  inputs:
    useConfigFile: true
    configFilePath: './GitVersion.yml'
    additionalArguments: '/updateprojectfiles'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'echo $(GitVersion.SemVer)'
